//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TanvirBakery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseHistory
    {
        public int Id { get; set; }
        public decimal Price { get; set; }
        public System.DateTime Date { get; set; }
        public int ProductId { get; set; }
        public int BuyerId { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual User User { get; set; }
    }
}
